# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2e3e5493ce0fb586edd10b98179a60780d7751b41c2231eedf0edf5133e30ab997fabe3cd88f86f9d5fb038f9e7fa68f9e8043e373142e2be48794fbc7cf963

test:
  secret_key_base: cedcaf59147f319daea92bab1d196b40aba17d5a98bb254e380b5ccfc85426e514c0b83d847914a05d0b2302a9f2c50cac5da22556084505456d1b11f6464a0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
